
%TTLs that are sent (and logged) are:
%54: start of experiment TRAINING
%55: start of experiment REAL (display of instructions)
%1: stimulus presentation ON
%2: stimulus presentation OFF & delay period 1 ON
%3: delay period 1 OFF & respond period ON
%4: response OLD and delay period 2 ON
%5: response NEW and delay period 2 ON
%6: dealy period 2 OFF
%66: end of experiment

EXPERIMENT_ON_TRAINING=55;
EXPERIMENT_ON_REAL=55;
STIMULUS_ON=1;
STIMULUS_OFF=2;
DELAY1_OFF=3;
RESPONSE_OLD=4;
RESPONSE_NEW=5;
DELAY2_OFF=6;
EXPERIMENT_ON=55;
EXPERIMENT_OFF=66;
DELAY3_OFF=7;
DELAY4_OFF=8;
DELAY5_OFF=9;
DELAY6_OFF=10;

REWARD_CUE_ON=91;
REWARD_CUE_OFF=92;

EXPECT_REWARD=80;
NOT_EXPECT_REWARD=81;
GOT_REWARD_NORMAL=82;
GOT_PUNISHMENT=83;
GOT_NEUTRAL=84;
GOT_REWARD_HIGH=85;
GOT_CONTROL=86;

RESPONSE_1=31;
RESPONSE_2=32;
RESPONSE_3=33;
RESPONSE_4=34;
RESPONSE_5=35;
RESPONSE_6=36;

RESPONSE_LEARNING_ANIMAL=20;
RESPONSE_LEARNING_NONANIMAL=21;

RESPONSE_COOPERATE=20;
RESPONSE_DEFECT=21;
OPPONENT_COOPERATE=22;
OPPONENT_DEFECT=23;


RESPONSE_YES=4;
RESPONSE_NO=5;

MODE_LEARN=100;
MODE_RECOG=200;

RESPONSE_LEFT=80;
RESPONSE_RIGHT=81;

%Only has 6 bits
TTL_DBS_START=55; %ON
TTL_DBS_END=60; %OFF
TTL_DBS_BUTTONPRESS=1;

%11-30 are random signal bits, reserved